Django_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('feedhub.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedhub/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)

app_name = 'feedhub'
urlpatterns = [
    path('', PostListView.as_view(), name='feed-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='feed-dtl'),
    path('post/new/', PostCreateView.as_view(), name='feed-new'),
    path('post/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='feed-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='feed-delete'),
    path('about/', views.about, name='feed-about'),
]

feedhub/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('feedhub:feed-dtl', kwargs={'pk':self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'


    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForms(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']


class UserInfoUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

feedhub/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
	ListView,
	DetailView,
	CreateView,
	UpdateView,
	DeleteView
)
from .models import Post


class PostListView(ListView):
	model = Post
	template_name = 'feedhub/home.html'
	context_object_name = 'feed'
	ordering = ['-date_posted']
	paginate_by = 6


class PostDetailView(DetailView):
	model = Post


class UserPostListView(ListView):
	model = Post
	template_name = 'feedhub/user_post.html'
	context_object_name = 'feed'
	paginate_by = 6

	def get_queryset(self):
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		return Post.objects.filter(author=user)

class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	fields = ['title', 'content']
	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Post
	fields = ['title', 'content']
	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Post
	success_url = '/'

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False


def about(request):
	context = {
		'title':'FeedHub | About'
	}
	return render(request, 'feedhub/about.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForms, UserInfoUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForms(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserRegisterForms()

    return render(request, 'users/register.html', {'form':form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserInfoUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Profile Updated!')
            return redirect('profile')
    else:
        u_form = UserInfoUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form' : u_form,
        'p_form' : p_form
    }
    return render(request, 'users/profile.html', context)

feedhub/templates/feedhub/about.html
{% extends "feedhub/base.html" %}
{% block content %}
	<h1>Its all about you in about</h1>
{% endblock content %}

feedhub/templates/feedhub/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'feedhub/main.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    {% if title %}
      <title>{{title}}</title>
    {% else %}
      <title>FeedHub</title>
    {%endif%}
</head>
<body style="background-color:rgba(0,0,0,0.1)">
  <header class="bg-dark w-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3 container">
      <a class="navbar-brand" href="{% url 'feedhub:feed-home' %}">FeedHub</a>
      <div class="collapse navbar-collapse d-flex flex-row-reverse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feedhub:feed-home' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'feedhub:feed-new' %}">Add Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feedhub:feed-about' %}">About</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container py-3" style="background-color:rgba(255,255,255,0.8);height:auto;">
    <div class="row">
      <section class="container col-7">
        {% if messages%}
          {%for msg in messages%}
            <div class="alert alert-{{msg.tags}} mt-3">
              {{msg}}
            </div>
          {%endfor%}
        {%endif%}
        {%block content%}
        {%endblock%}
      </section>
      {% if "login" in request.path or "password" in request.path or "register" in request.path %}
        <section style="display:none;">
          <div class="container m-2 p-1">
            <h3 class="text-center">Search Bar</h3>
          </div>
        </section>
      {%else%}
        <section class="container col-3 border h-50">
          <div class="container m-2 p-1">
            <h3 class="text-center">Search Bar</h3>
          </div>
        </section>
      {% endif %}
    </div>
  </main>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>

feedhub/templates/feedhub/home.html
{% extends "feedhub/base.html" %}
{% block content %}
	{% for post in feed %}
		<div class="container mb-3 py-2 _stpbx border-top rounded shadow-sm">
				<div class="d-inline-flex border-bottom mb-2 p-2">
					<img class="_usrlg" width="50px" height="50px" src="{{post.author.profile.image.url}}" alt="profile_pic">
					<div>
						<h2><a href="{% url 'feedhub:user-posts' post.author.username %}">{{ post.author }}</a></h2>
						<small>Posted on - {{ post.date_posted|date:"F j, Y"}}</small>
					</div>
				</div>
				<h3> <a href="{% url 'feedhub:feed-dtl' post.id %}">{{post.title}}</a> </h3>
				<p>{{ post.content }}</p>
		</div>
	{%endfor%}
	{% if is_paginated %}
		<div class="pagination mx-3 py-2 d-flex justify-content-center">
			<span class="step-links">
				{% if page_obj.has_previous %}
						<a href="?page=1" class="btn btn-outline-info mx-1">&laquo; First</a>
						<a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info">Previous</a>
				{% endif %}
				{% for pn in page_obj.paginator.page_range %}
					{% if pn == page_obj.number %}
						<a href="#" class="btn btn-primary disabled">{{pn}}</a>
					{%elif pn > page_obj.number|add:-3 and pn < page_obj.number|add:3 %}
						<a href="?page={{pn}}" class="btn btn-outline-primary">{{pn}}</a>
					{% endif %}
				{% endfor %}
				{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mx-1">Next</a>
						<a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info">Last &raquo;</a>
				{% endif %}
			</span>
		</div>
	{% endif %}
{% endblock content %}

feedhub/templates/feedhub/post_confirm_delete.html
{% extends "feedhub/base.html" %}
{% block content %}
	<div class="content-section container w-50 mt-3">
    <form method="post">
      {%csrf_token%}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Post</legend>
        <h2>Are you sure, You want to delete '{{object.title}}' ?</h2>
      </fieldset>
      <button class="btn btn-danger my-3" type="submit">Yes, Delete</button>
      <a class="btn btn-info my-3" href="{% url 'feedhub:feed-dtl' object.id %}">Cancel</a>
    </form>
  </div>
{% endblock content %}

feedhub/templates/feedhub/post_detail.html
{% extends "feedhub/base.html" %}
{% block content %}
	<div class="container mb-3 py-2 _stpbx border-top rounded shadow-sm">
			<div class="d-inline-flex border-bottom mb-2 p-2">
				<img class="_usrlg" width="50px" height="50px" src="{{object.author.profile.image.url}}" alt="profile_pic">
				<div>
					<h2><a href="{% url 'feedhub:user-posts' object.author.username %}">{{ object.author }}</a></h2>
					<small>Posted on - {{ object.date_posted|date:"F j, Y"}}</small>
				</div>
				{% if user == object.author %}
					<div class="mx-3">
						<a href="{% url 'feedhub:feed-update' object.id %}" class="btn btn-info mx-1">Update</a>
						<a href="{% url 'feedhub:feed-delete' object.id %}" class="btn btn-danger">Delete</a>
					</div>
				{%endif%}
			</div>
			<p>{{ object.content }}</p>
	</div>
{% endblock content %}

feedhub/templates/feedhub/post_form.html
{% extends "feedhub/base.html" %}
{%load crispy_forms_tags%}
{% block content %}
	<div class="content-section container w-50 mt-3">
    <form method="post">
      {%csrf_token%}
      <fieldset class="form-group">
				{% if "new" in request.path %}
        	<legend class="border-bottom mb-4">New Post</legend>
				{% else %}
					<legend class="border-bottom mb-4">Update Post</legend>
				{%endif%}
        {{form|crispy}}
      </fieldset>
      <button class="btn btn-dark my-3" type="submit">Post</button>
    </form>
  </div>
{% endblock content %}

feedhub/templates/feedhub/user_post.html
{% extends "feedhub/base.html" %}
{% block content %}
  <h1 class="m-2">{{view.kwargs.username}} ({{page_obj.paginator.count}})</h1>
	{% for post in feed %}
		<div class="container mb-3 py-2 _stpbx border-top rounded shadow-sm">
				<div class="d-inline-flex border-bottom mb-2 p-2">
					<img class="_usrlg" width="50px" height="50px" src="{{post.author.profile.image.url}}" alt="profile_pic">
					<div>
						<h2><a href="{% url 'feedhub:user-posts' post.author.username %}">{{ post.author }}</a></h2>
						<small>Posted on - {{ post.date_posted|date:"F j, Y"}}</small>
					</div>
				</div>
				<h3> <a href="{% url 'feedhub:feed-dtl' post.id %}">{{post.title}}</a> </h3>
				<p>{{ post.content }}</p>
		</div>
	{%endfor%}
  {% if is_paginated %}
    <div class="pagination mx-3 py-2 d-flex justify-content-center">
      <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-outline-info mx-1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info">Previous</a>
        {% endif %}
        {% for pn in page_obj.paginator.page_range %}
          {% if pn == page_obj.number %}
            <a href="#" class="btn btn-primary disabled">{{pn}}</a>
          {%elif pn > page_obj.number|add:-3 and pn < page_obj.number|add:3 %}
            <a href="?page={{pn}}" class="btn btn-outline-primary">{{pn}}</a>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mx-1">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info">Last &raquo;</a>
        {% endif %}
      </span>
    </div>
  {% endif %}
{% endblock content %}

users/templates/users/login.html
{% extends "feedhub/base.html" %}
{%load crispy_forms_tags%}
{% block content %}
	<div class="content-section container w-50 mt-3">
    <form method="post">
      {%csrf_token%}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Login</legend>
        {{form|crispy}}
      </fieldset>
      <button class="btn btn-dark my-3" type="submit">Login</button>
			<small class="text-muted mx-2">
        <a href="{%url 'password_reset' %}" class="ml-2">Forgot Password ?</a>
      </small>
    </form>
    <div class="border-top pt3">
      <small class="text-muted">
        Don't have an account? <a href="{%url 'register'%}" class="ml-2">SignUp</a>
      </small>
    </div>
  </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "feedhub/base.html" %}
{% block content %}
	<h2>You have been loged out!</h2>
  <a href="{%url 'login'%}" class="mt-2">Login Again</a>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "feedhub/base.html" %}
{%load crispy_forms_tags%}
{% block content %}
	<div class="content-section container w-50 mt-3">
    <form method="post">
      {%csrf_token%}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Password Reset</legend>
        {{form|crispy}}
      </fieldset>
      <button class="btn btn-dark my-3" type="submit">Request Password Reset</button>
    </form>
  </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "feedhub/base.html" %}
{%load crispy_forms_tags%}
{% block content %}
	<div class="alert alert-info">
    Your password has been reset successfully.
  </div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "feedhub/base.html" %}
{%load crispy_forms_tags%}
{% block content %}
	<div class="content-section container w-50 mt-3">
    <form method="post">
      {%csrf_token%}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Reset Password</legend>
        {{form|crispy}}
      </fieldset>
      <button class="btn btn-dark my-3" type="submit">Confirm Reset</button>
    </form>
  </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "feedhub/base.html" %}
{%load crispy_forms_tags%}
{% block content %}
	<div class="alert alert-info">
    An Email for password reset has been send to you. Please check your email.
  </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "feedhub/base.html" %}
{%load crispy_forms_tags%}
{% block content %}
	<div class="container p-2 d-inline-flex shadow-sm border-top row">
		<div class="col-2"><img src="{{user.profile.image.url}}" class="_usrlg" alt="userprofile" width="100px" height="100px"></div>
		<div class="col-8">
			<h2>{{user.username}}</h2>
			<small class="mt-2">{{user.email}}</small>
		</div>
	</div>
	<div class="p-2 m-2 border-top">
		<form method="post" enctype="multipart/form-data">
      {%csrf_token%}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Update Profile</legend>
        {{u_form|crispy}}
				{{p_form|crispy}}
      </fieldset>
      <button class="btn btn-outline-info" type="submit">Update</button>
    </form>
	</div>
  <a href="{%url 'logout'%}" class="mt-2">Logout</a>
{% endblock content %}

users/templates/users/register.html
{% extends "feedhub/base.html" %}
{%load crispy_forms_tags%}
{% block content %}
	<div class="content-section">
    <form method="post">
      {%csrf_token%}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Join Today</legend>
        {{form|crispy}}
      </fieldset>
      <button class="btn btn-outline-info" type="submit">Submit</button>
    </form>
    <div class="border-top pt3">
      <small class="text-muted">
        Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
      </small>
    </div>
  </div>
{% endblock content %}